COURSE_NAMES = [
	"Advanced Computer Architecture",
	"Advances in Robotics and Control",
	"Alternate Religious Traditions in India History",
	"An Introduction to William Blake",
	"Cognitive Neuroscience",
	"Computer Vision",
	"Comprehension of Indian Music",
	"Design of Hydraulic Structures",
	"Digital VLSI Design",
	"Database Systems",
	"Deep Learning: Theory and Practices",
	"Distributed Systems",
	"Digital Humanities Project",
	"Differential Equations",
	"Disaster Management",
	"Earthquake Engineering",
	"Elasticity: Theory and Finite Elements",
	"Environment and Politics in India",
	"Ethics",
	"Fiber Optic Communication Systems",
	"Flexible Electronics",
	"Fiber Optic Communication Systems",
	"General & Structural Chemistry",
	"Gender and Society",
	"Green Buildings",
	"Hydroinformatics",
	"ICTs for Development",
	"Introduction to Coding Theory",
	"Introduction to Neural and Cognitive Modeling",
	"Introduction to Game Theory",
	"Information Security Audit and Assurance",
	"Intro to Robotics: Mechanics & Control",
	"Introduction to parallel Scientific Computing",
	"Introduction to Systems Biology",
	"Internals of Application Servers",
	"Linguistics Data 2: Collection & Modeling",
	"Language, Mind and Society",
	"Modeling and Simulations",
	"Music, Mind and Technology",
	"Multivariate Analysis",
	"NGS Data Analysis",
	"NLP Applications",
	"Optimization Methods",
	"Photonics",
	"Probabilistic Graphical Models",
	"Principles of Information Security",
	"Remote Sensing",
	"Science Technology and Society",
	"Signal Detection and Estimation Theory",
	"Social Computing",
	"Software Engineering",
	"Software Foundations",
	"Stability of Structures",
	"Statistical Methods in AI",
	"System and Network Security",
	"Time Frequency Analysis",
	"The State in Colonial India",
	"Topics in Coding Theory",
	"Topics in Nano Sciences",
	"Usability Engineering",
	"Analog Electronic Circuits",
	"Classical Mechanics",
	"Computer Systems Organization",
	"Computing in Sciences-II",
	"Computational Linguistics-I",
	"Communications and Controls in IoT",
	"Communication Networks",
	"Communication Theory I",
	"Data Structures and Algorithms",
	"Data Visualizaion",
	"Digital signal Analysis",
	"Electronics Workshop II",
	"Electrodynamics",
	"General and Structural Chemistry",
	"Introduction to Brain and Cognition",
	"Introduction to Bioelectronics",
	"Introduction to Information Security",
	"Introduction to Quantum Information and Computation",
	"Intro to Human Sciences",
	"Introduction to Software Systems",
	"Introduction to IoT",
	"Information and Communication",
	"Introduction to Linguistics-II",
	"Introduction to Processor Architecture",
	"Machine, Data and Learning",
	"Making of the Contemporary India",
	"Linear Algebra",
	"Program Verification",
	"Science-II(New)",
	"Science II(Old)",
	"Science Lab-II",
	"Software Programming for Performance",
	"Statistical Mechanics",
	"Thermodynamics",
	"Thinking and Knowing in the Human Sciences-1",
	"Algorithm Analysis and Design",
	"Algorithms & Operating Systems",
	"Bioinformatics(H1)",
	"Chemical Kinetics and Reaction Dynamics (H2)",
	"Classical Text Readings - I",
	"Communication and Controls in IoT",
	"Computational Linguistics II: Comp Semantics and Discourse parsing",
	"Computer Programming",
	"Operating Systems and Networks",
	"Computing in Sciences-1(H)",
	"Data and Applications (H2)",
	"Digital Systems and Microcontrollers",
	"Discrete Structures",
	"Electronic Workshop-1 (H2)",
	"Human Sciences Lab-1 (H2)",
	"Introduction to Biology",
	"Introduction to Linguistics-1",
	"Language and Society",
	"Making of Contemporary World",
	"Networks Signals and Systems",
	"Probability and Random Processes",
	"Probability and Statistics",
	"Quantum Mechanics",
	"Real Analysis",
	"Science I",
	"Signal Processing",
	"Spectroscopy(H1)",
	"Systems Biology(H2)",
	"Systems Thinking",
	"Thinking and Knowing in the Human Sciences - II",
	"Advanced Graphics, AR & VR",
	"Advanced Biomolecular Architecture",
	"Advanced Computer Networks",
	"Advanced Data Systems",
	"Advanced NLP",
	"Advanced Structural Design",
	"Analog IC Design",
	"Behavioral Research & Experimental Design",
	"Biomolecular Structure Interaction & Dynamics",
	"CMOS Radio Frequency Integrated Circuit Design",
	"Compilers",
	"Concurrent Data Structures",
	"Critical Viewing and Reading",
	"Data Analytics I",
	"Data Systems",
	"Design for Testability",
	"Digital Image Processing",
	"Distributed Systems",
	"Distributing Trust and Block Chains",
	"Entropy and Information",
	"Environmental Science & Technology",
	"Finite Element Methods",
	"Functional Analysis",
	"Game Design and Engineering",
	"Gender and Society",
	"Hydrological modelling and Software Development",
	"Illumination Engineering",
	"Information Retrieval & Extraction",
	"Intro to Cognitive Science",
	"Intro to Psychology",
	"Introduction to History",
	"Introduction to Neural and Cognitive Modeling",
	"Introduction to Philosophy",
	"Introduction to Shakespeare",
	"Introduction to Sociology",
	"IS Codes on Design and Structural Safety Assessment",
	"Mobile Robotics",
	"Modern Complexity Theory",
	"Molecular symmetry and quantum mechanics",
	"Open Quantum Systems and Quantum Thermodynamics",
	"Plastic Theory of Structures",
	"Principles of Information Security",
	"Principles of Programming Languages",
	"Principles of Semiconductor Devices",
	"Real-Time Systems",
	"Research in Information Security",
	"Robotics: Dynamics and Control",
	"Selected topics in Instrumental Analysis",
	"Social Science Perspective on HCI",
	"Spatial Informatics",
	"Speech Signal Processing",
	"Statistical Methods in AI",
	"Structural Wind Engineering",
	"Technology Product Entrepreneurship",
	"Theories and Practices of Nationalism",
	"Topics in Applied Optimization",
	"Topics in Machine Learning",
	"Understanding Raga: Semi Classical Forms of Indian Music",
	"Wireless Communications"
]